spring:
  thymeleaf:
    cache=false
  datasource:
    url: "jdbc:postgresql://localhost:5432/tacocloud"
    username: "marina"
    password: "28052000"
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      base-path: /data-api
taco:
  orders:
    pageSize: 10
logging:
  file:
    path: /var/logs/
    name: TacoCloud.log
  level:
    root: WARN
    org.springframework.security: DEBUG
#server:
#  port: 8443
#  ssl:
#    key-store: classpath:mykeys.jks
#    key-store-password: 876782
#    key-password: 876782
# можно использовать одни свойства внутри других с помощью маркеров-заполнителей ${}
greeting:
  welcome: ${spring.application.name}