spring:
  thymeleaf:
    cache=false
  datasource:
    url: "jdbc:postgresql://localhost:5432/tacocloud"
    username: "marina"
    password: "28052000"
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: <facebook client id>
            client-secret: <facebook client secret>
            scope: email, public_profile