spring:
  thymeleaf:
    cache=false
  datasource:
    url: "jdbc:postgresql://localhost:5432/tacocloud"
    username: "marina"
    password: "28052000"
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      springframework: DEBUG