spring:
  thymeleaf:
    cache=false
  datasource:
    url: "jdbc:postgresql://localhost:5432/tacocloud"
    username: "marina"
    password: "28052000"
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: schema.sql
      data-source-class-name: data.sql
#logging:
#  level:
#    org:
#      springframework: DEBUG
server:
  port: 9090